
#------------------------------------------------------------------------
# the docker-access stack defines Docker Swarm services that control access
# to the Docker engine for enhanced security; these services run as single
# tasks (containers) on the swarm-manager node
#------------------------------------------------------------------------

# use docker-compose v3 to enable Swarm deploy and stacks
version: "3.8"
  
services:
    # read-only proxy to docker engine on the manager node, to be used by Traefik
    socket-proxy:
        image: tecnativa/docker-socket-proxy
        volumes:
            # only the proxy has access to the docker engine directly
            # even here, make the mount be read only
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            # only enable Docker API requests needed for service discovery (GET but not POST, etc.)
            # here, "1" means "true" or "allow"
            SERVICES: 1
            TASKS: 1
            NETWORKS: 1
        networks:
            # only enable requests from containers on a dedicated network
            - docker-access
        deploy:
            # must run on our one designated swarm manager node
            replicas: 1
            placement:
                constraints:
                    - node.labels.swarm-manager-node==true
networks:
    # network for Traefik to poll docker engine via read-only proxy
    docker-access:
        external: true

